### ISSUE TITLE
Completar README.md

### ISSUE THREAD

**Issue by Juliauru** [aigora/twE100-central_parking#1]
Hola, 
Debéis completar en el README.md la información del trabajo, y ya podéis ir subiendo una primera versión del menú que utilizaréis para vuestro programa, u otros puntos de código inicial. 
Si tenéis dudas sobre como completar el README.md o sobre como subir archivos u otras cosas ,tenéis toda la información en el repositorio llamado _Punto_inicio_.
No se si el grupo es de más de una persona, si es así se cerrará el plazo para entrar en los grupos la semana que viene, así que ,¡Corred!

**Comment by Diegome** [comment]
Hola,
El grupo lo conformará si es posible una sola persona. 
Esta de nuevo subido el archivo README.md con la información del trabajo. (Estuve trabajando con GITHUB DESKTOP y debí de borrar por error el archivo o hacer un commit sobre un archivo README sin modificar).

**Comment by Juliauru** [comment]
Vale, eso lo tienes que hablar con tu profesor, pero creo que siendo de el E100 si es posible. 
Cosas que pasan al empezar, pero seguro que terminas por entienderlo todo!
