### ISSUE TITLE
Sólo un archivo .cpp/.c

### ISSUE THREAD

**Issue by Juliauru** [aigora/twE100-central_parking#2]
Hola, 
No se muy bien cual es el contenido de vuestros archivos, pero, si son diferentes versiones del mismo programa debéis subirlo con el mismo nombre para que el control de versiones funcione correctamente. 
Solo debéis trabajar con un solo archivo que vayáis modificando para poder ver los cambios realizados.

**Comment by Diegome** [comment]
De acuerdo, desconocía el funcionamiento del control de versiones, subiré las distintas versiones con el mismo nombre de archivo así como las las próximas actualizaciones, gracias por la información.
